In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("diabetes.csv")
df

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1
...,...,...,...,...,...,...,...,...,...
763,10,101,76,48,180,32.9,0.171,63,0
764,2,122,70,27,0,36.8,0.340,27,0
765,5,121,72,23,112,26.2,0.245,30,0
766,1,126,60,0,0,30.1,0.349,47,1
767,1,93,70,31,0,30.4,0.315,23,0

In [3]:
X = df.drop("Outcome", axis=1)

In [4]:
X

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age
0,6,148,72,35,0,33.6,0.627,50
1,1,85,66,29,0,26.6,0.351,31
2,8,183,64,0,0,23.3,0.672,32
3,1,89,66,23,94,28.1,0.167,21
4,0,137,40,35,168,43.1,2.288,33
...,...,...,...,...,...,...,...,...
763,10,101,76,48,180,32.9,0.171,63
764,2,122,70,27,0,36.8,0.340,27
765,5,121,72,23,112,26.2,0.245,30
766,1,126,60,0,0,30.1,0.349,47
767,1,93,70,31,0,30.4,0.315,23

In [5]:
y = df["Outcome"]

In [6]:
y

0      1
1      0
2      1
3      0
4      1
      ..
763    0
764    0
765    0
766    1
767    0
Name: Outcome, Length: 768, dtype: int64

In [7]:
from sklearn.model_selection import train_test_split

In [8]:
X, y

(     Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
 0              6      148             72             35        0  33.6
 1              1       85             66             29        0  26.6
 2              8      183             64              0        0  23.3
 3              1       89             66             23       94  28.1
 4              0      137             40             35      168  43.1
 ..           ...      ...            ...            ...      ...   ...
 763           10      101             76             48      180  32.9
 764            2      122             70             27        0  36.8
 765            5      121             72             23      112  26.2
 766            1      126             60              0        0  30.1
 767            1       93             70             31        0  30.4

      DiabetesPedigreeFunction  Age
 0                       0.627   50
 1                       0.351   31
 2                       0.672   32
 3                       0.167   21
 4                       2.288   33
 ..                        ...  ...
 763                     0.171   63
 764                     0.340   27
 765                     0.245   30
 766                     0.349   47
 767                     0.315   23

 [768 rows x 8 columns],
 0      1
 1      0
 2      1
 3      0
 4      1
       ..
 763    0
 764    0
 765    0
 766    1
 767    0
 Name: Outcome, Length: 768, dtype: int64)

In [9]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

In [10]:
X_train,  y_train, X_test, y_test

(     Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
 464           10      115             98              0        0  24.0
 223            7      142             60             33      190  28.8
 393            4      116             72             12       87  22.1
 766            1      126             60              0        0  30.1
 570            3       78             70              0        0  32.5
 ..           ...      ...            ...            ...      ...   ...
 71             5      139             64             35      140  28.6
 106            1       96            122              0        0  22.4
 270           10      101             86             37        0  45.6
 435            0      141              0              0        0  42.4
 102            0      125             96              0        0  22.5

      DiabetesPedigreeFunction  Age
 464                     1.022   34
 223                     0.687   61
 393                     0.463   37
 766                     0.349   47
 570                     0.270   39
 ..                        ...  ...
 71                      0.411   26
 106                     0.207   27
 270                     1.136   38
 435                     0.205   29
 102                     0.262   21

 [514 rows x 8 columns],
 464    0
 223    0
 393    0
 766    1
 570    0
       ..
 71     0
 106    0
 270    1
 435    1
 102    0
 Name: Outcome, Length: 514, dtype: int64,
      Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
 668            6       98             58             33      190  34.0
 324            2      112             75             32        0  35.7
 624            2      108             64              0        0  30.8
 690            8      107             80              0        0  24.6
 473            7      136             90              0        0  29.9
 ..           ...      ...            ...            ...      ...   ...
 311            0      106             70             37      148  39.4
 429            1       95             82             25      180  35.0
 182            1        0             74             20       23  27.7
 586            8      143             66              0        0  34.9
 679            2      101             58             17      265  24.2

      DiabetesPedigreeFunction  Age
 668                     0.430   43
 324                     0.148   21
 624                     0.158   21
 690                     0.856   34
 473                     0.210   50
 ..                        ...  ...
 311                     0.605   22
 429                     0.233   43
 182                     0.299   21
 586                     0.129   41
 679                     0.614   23

 [254 rows x 8 columns],
 668    0
 324    0
 624    0
 690    0
 473    0
       ..
 311    0
 429    1
 182    0
 586    1
 679    0
 Name: Outcome, Length: 254, dtype: int64)

In [11]:
random_state = 42

In [12]:
X_train

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age
464,10,115,98,0,0,24.0,1.022,34
223,7,142,60,33,190,28.8,0.687,61
393,4,116,72,12,87,22.1,0.463,37
766,1,126,60,0,0,30.1,0.349,47
570,3,78,70,0,0,32.5,0.270,39
...,...,...,...,...,...,...,...,...
71,5,139,64,35,140,28.6,0.411,26
106,1,96,122,0,0,22.4,0.207,27
270,10,101,86,37,0,45.6,1.136,38
435,0,141,0,0,0,42.4,0.205,29
102,0,125,96,0,0,22.5,0.262,21

In [13]:
y_train

464    0
223    0
393    0
766    1
570    0
      ..
71     0
106    0
270    1
435    1
102    0
Name: Outcome, Length: 514, dtype: int64

In [14]:
X_test

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age
668,6,98,58,33,190,34.0,0.430,43
324,2,112,75,32,0,35.7,0.148,21
624,2,108,64,0,0,30.8,0.158,21
690,8,107,80,0,0,24.6,0.856,34
473,7,136,90,0,0,29.9,0.210,50
...,...,...,...,...,...,...,...,...
311,0,106,70,37,148,39.4,0.605,22
429,1,95,82,25,180,35.0,0.233,43
182,1,0,74,20,23,27.7,0.299,21
586,8,143,66,0,0,34.9,0.129,41
679,2,101,58,17,265,24.2,0.614,23

In [15]:
y_test

668    0
324    0
624    0
690    0
473    0
      ..
311    0
429    1
182    0
586    1
679    0
Name: Outcome, Length: 254, dtype: int64

In [16]:
from sklearn.model_selection import KFold

In [17]:
kf = KFold(n_splits=2, shuffle=True)

In [18]:
kf.split(X)

In [19]:
for train, val in kf.split(X):
    print("Training indicies:", train)
    print("Validation indicies:", val)

Training indicies: [  0   1   4   6   8  13  14  22  24  25  26  27  29  32  33  34  36  37
  41  42  44  45  49  50  51  53  54  59  60  61  62  63  64  66  68  70
  71  72  75  77  79  82  85  87  88  90  91  95  96  97  99 101 103 104
 106 108 109 114 115 117 120 123 124 128 132 134 136 139 140 143 145 146
 147 150 152 155 156 158 160 163 166 170 172 173 174 176 178 180 181 182
 185 186 187 189 191 192 193 196 197 200 201 203 206 212 213 218 221 224
 225 226 229 234 235 236 238 239 240 241 242 243 244 245 247 248 252 255
 256 257 260 264 268 269 271 272 274 275 276 279 282 283 284 285 286 288
 290 291 292 293 294 295 298 299 300 301 302 303 305 307 308 309 310 313
 321 322 323 325 329 330 331 333 336 338 340 342 344 345 346 348 349 351
 354 355 356 359 362 364 365 366 367 370 371 372 374 375 376 378 379 380
 381 383 385 387 389 390 393 399 401 406 407 409 410 412 414 417 427 429
 430 433 434 436 437 439 441 446 447 448 449 454 455 456 458 459 461 462
 470 471 473 474 476 477 478 480 482 484 486 489 492 494 495 500 501 502
 503 504 505 507 509 510 512 514 518 521 524 526 531 532 533 537 539 544
 548 551 552 554 557 558 560 561 565 566 567 568 569 570 573 574 575 577
 580 581 582 584 585 588 590 591 592 595 597 600 601 602 604 608 610 611
 614 615 620 622 625 626 630 631 632 633 636 637 640 641 642 646 652 653
 657 658 661 662 663 664 665 666 667 668 671 672 673 674 677 679 684 685
 687 690 691 692 693 694 695 698 699 700 701 708 710 711 712 715 716 722
 725 732 734 735 736 737 738 739 740 741 742 743 744 749 750 753 754 757
 758 761 762 764 765 767]
Validation indicies: [  2   3   5   7   9  10  11  12  15  16  17  18  19  20  21  23  28  30
  31  35  38  39  40  43  46  47  48  52  55  56  57  58  65  67  69  73
  74  76  78  80  81  83  84  86  89  92  93  94  98 100 102 105 107 110
 111 112 113 116 118 119 121 122 125 126 127 129 130 131 133 135 137 138
 141 142 144 148 149 151 153 154 157 159 161 162 164 165 167 168 169 171
 175 177 179 183 184 188 190 194 195 198 199 202 204 205 207 208 209 210
 211 214 215 216 217 219 220 222 223 227 228 230 231 232 233 237 246 249
 250 251 253 254 258 259 261 262 263 265 266 267 270 273 277 278 280 281
 287 289 296 297 304 306 311 312 314 315 316 317 318 319 320 324 326 327
 328 332 334 335 337 339 341 343 347 350 352 353 357 358 360 361 363 368
 369 373 377 382 384 386 388 391 392 394 395 396 397 398 400 402 403 404
 405 408 411 413 415 416 418 419 420 421 422 423 424 425 426 428 431 432
 435 438 440 442 443 444 445 450 451 452 453 457 460 463 464 465 466 467
 468 469 472 475 479 481 483 485 487 488 490 491 493 496 497 498 499 506
 508 511 513 515 516 517 519 520 522 523 525 527 528 529 530 534 535 536
 538 540 541 542 543 545 546 547 549 550 553 555 556 559 562 563 564 571
 572 576 578 579 583 586 587 589 593 594 596 598 599 603 605 606 607 609
 612 613 616 617 618 619 621 623 624 627 628 629 634 635 638 639 643 644
 645 647 648 649 650 651 654 655 656 659 660 669 670 675 676 678 680 681
 682 683 686 688 689 696 697 702 703 704 705 706 707 709 713 714 717 718
 719 720 721 723 724 726 727 728 729 730 731 733 745 746 747 748 751 752
 755 756 759 760 763 766]
Training indicies: [  2   3   5   7   9  10  11  12  15  16  17  18  19  20  21  23  28  30
  31  35  38  39  40  43  46  47  48  52  55  56  57  58  65  67  69  73
  74  76  78  80  81  83  84  86  89  92  93  94  98 100 102 105 107 110
 111 112 113 116 118 119 121 122 125 126 127 129 130 131 133 135 137 138
 141 142 144 148 149 151 153 154 157 159 161 162 164 165 167 168 169 171
 175 177 179 183 184 188 190 194 195 198 199 202 204 205 207 208 209 210
 211 214 215 216 217 219 220 222 223 227 228 230 231 232 233 237 246 249
 250 251 253 254 258 259 261 262 263 265 266 267 270 273 277 278 280 281
 287 289 296 297 304 306 311 312 314 315 316 317 318 319 320 324 326 327
 328 332 334 335 337 339 341 343 347 350 352 353 357 358 360 361 363 368
 369 373 377 382 384 386 388 391 392 394 395 396 397 398 400 402 403 404
 405 408 411 413 415 416 418 419 420 421 422 423 424 425 426 428 431 432
 435 438 440 442 443 444 445 450 451 452 453 457 460 463 464 465 466 467
 468 469 472 475 479 481 483 485 487 488 490 491 493 496 497 498 499 506
 508 511 513 515 516 517 519 520 522 523 525 527 528 529 530 534 535 536
 538 540 541 542 543 545 546 547 549 550 553 555 556 559 562 563 564 571
 572 576 578 579 583 586 587 589 593 594 596 598 599 603 605 606 607 609
 612 613 616 617 618 619 621 623 624 627 628 629 634 635 638 639 643 644
 645 647 648 649 650 651 654 655 656 659 660 669 670 675 676 678 680 681
 682 683 686 688 689 696 697 702 703 704 705 706 707 709 713 714 717 718
 719 720 721 723 724 726 727 728 729 730 731 733 745 746 747 748 751 752
 755 756 759 760 763 766]
Validation indicies: [  0   1   4   6   8  13  14  22  24  25  26  27  29  32  33  34  36  37
  41  42  44  45  49  50  51  53  54  59  60  61  62  63  64  66  68  70
  71  72  75  77  79  82  85  87  88  90  91  95  96  97  99 101 103 104
 106 108 109 114 115 117 120 123 124 128 132 134 136 139 140 143 145 146
 147 150 152 155 156 158 160 163 166 170 172 173 174 176 178 180 181 182
 185 186 187 189 191 192 193 196 197 200 201 203 206 212 213 218 221 224
 225 226 229 234 235 236 238 239 240 241 242 243 244 245 247 248 252 255
 256 257 260 264 268 269 271 272 274 275 276 279 282 283 284 285 286 288
 290 291 292 293 294 295 298 299 300 301 302 303 305 307 308 309 310 313
 321 322 323 325 329 330 331 333 336 338 340 342 344 345 346 348 349 351
 354 355 356 359 362 364 365 366 367 370 371 372 374 375 376 378 379 380
 381 383 385 387 389 390 393 399 401 406 407 409 410 412 414 417 427 429
 430 433 434 436 437 439 441 446 447 448 449 454 455 456 458 459 461 462
 470 471 473 474 476 477 478 480 482 484 486 489 492 494 495 500 501 502
 503 504 505 507 509 510 512 514 518 521 524 526 531 532 533 537 539 544
 548 551 552 554 557 558 560 561 565 566 567 568 569 570 573 574 575 577
 580 581 582 584 585 588 590 591 592 595 597 600 601 602 604 608 610 611
 614 615 620 622 625 626 630 631 632 633 636 637 640 641 642 646 652 653
 657 658 661 662 663 664 665 666 667 668 671 672 673 674 677 679 684 685
 687 690 691 692 693 694 695 698 699 700 701 708 710 711 712 715 716 722
 725 732 734 735 736 737 738 739 740 741 742 743 744 749 750 753 754 757
 758 761 762 764 765 767]